### ISSUE TITLE
How  differentiate small 3d objects from 3D Volume ?using How to remove small object [3d volume] using cc3d.connected_components?

### ISSUE THREAD

**Issue by selvakarna** [seung-lab/connected-components-3d#22] opened 2019-06-18 07:40 UTC
How differentiate small 3d objects from 3D Volume ?using How to remove small object [3d volume] using cc3d.connected_components?

**Comment by william-silversmith** [comment] 2019-06-18 15:17
I think this is a duplicate of #21 so I'm going to close this. Please reopen if there's a difference!

**Closed by william-silversmith** 2019-06-18 15:17 UTC
Labels: question
